### ISSUE TITLE
Fichier .pyrrhaci.yml

### ISSUE THREAD

**Issue by PonteIneptique** [Chartes-TNAH/pyrrhaCI#7]
Un fichier `.pyrrhaci.yml` peut-être fourni 

```yaml
- ignore:
  - "5::ForbiddenDeLemma"
  - "185:A:llowedOnly"
  - ":lemma_index:Message"
- additional_rules : "additional_rules.tsv"
- allowed_lemma: "lemma.txt"
- allowed_pos: "POS.txt"
- allowed_morph: "morph.tsv"
```

Les clefs sous `ignore` permettent d'ignorer des messages d'erreurs. Ils sont sous la forme `index_de_catégorie_erreur:index_de_token:Message_pour_se_rappeler_pourquoi`

Un second fichier de règles peut être fourni.
